name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Setiap hari sekali
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
          output: dist/trophy.svg

      - name: Push trophy.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: trophy-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}